#!/bin/bash

echo "🧪 TEST DE CONNEXION MONGODB ATLAS"
echo "=================================="
echo ""

echo "📋 ÉTAPES À FAIRE AVANT CE TEST:"
echo "1. ✅ Créer compte MongoDB Atlas"
echo "2. ✅ Créer cluster gratuit (M0)"
echo "3. ✅ Créer utilisateur base de données"
echo "4. ✅ Autoriser accès réseau (0.0.0.0/0)"
echo "5. ✅ Récupérer chaîne de connexion"
echo "6. ✅ Modifier /app/backend/.env avec ta chaîne Atlas"
echo "7. ✅ Uploader les données avec mongorestore"
echo ""

echo "🔧 COMMANDES DE TEST:"
echo ""
echo "# 1. Tester la connexion Atlas"
echo "mongosh \"TA_CHAINE_ATLAS\""
echo ""
echo "# 2. Vérifier tes données"
echo "use avimarche_db"
echo "show collections"
echo "db.users.countDocuments({})"
echo "db.products.countDocuments({})"
echo ""
echo "# 3. Redémarrer ton application"
echo "sudo supervisorctl restart backend"
echo ""
echo "# 4. Tester l'API"
echo "curl http://localhost:8001/api/stats/dashboard"
echo ""

echo "🎉 Si tout marche, tes données sont dans le cloud!"
echo "🌐 Ton site pourra maintenant fonctionner en ligne!"